

  unit-tests:
    name: Unit Tests
    needs: [setup]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      issues: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run Pester Unit Tests
        uses: ./.github/actions/ps-unit-tests
        with:
          module-list: ${{ needs.setup.outputs.module-list }}

  static-code-analysis:
    name: Static Code Analysis
    needs: [setup]
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run PSScriptAnalyzer
        uses: ./.github/actions/ps-static-code-analysis
        with:
          module-list: ${{ needs.setup.outputs.module-list }}

  code-injection:
    name: Code Injection
    needs: [setup]
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run InjectionHunter
        uses: ./.github/actions/ps-code-injection
        with:
          module-list: ${{ needs.setup.outputs.module-list }}

  semantic-code-analysis:
    name: Semantic Code Analysis
    needs: [setup]
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: actions
          build-mode: none
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:${{matrix.language}}"

  build:
    name: Build
    needs: [setup, unit-tests, static-code-analysis, code-injection, semantic-code-analysis]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release-version: ${{ steps.build.outputs.release-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          fetch-depth: 0
      - name: Build Module
        id: build
        uses: ./.github/actions/ps-build
        with:
          release-type: 'Debug'
          module-list: ${{ needs.setup.outputs.module-list }}

  integration-tests:
    name: Integration Tests
    needs: [setup, build]
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-v${{ needs.build.outputs.release-version }}
          path: build
      - name: Run Integration Tests
        uses: ./.github/actions/ps-integration-tests
        with:
          module-list: ${{ needs.setup.outputs.module-list }}
