name: "CI Semantic Code Analysis"
on:
  workflow_call:
  schedule:
    - cron: '27 2 * * 1'

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.01

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@4f3212b61783c3c68e8309a0f18a212f1af0fadd # v4
        with:
          languages: actions # PowerShell is not supported natively yet
          build-mode: none

      # Runs the CodeQL analysis.
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@4f3212b61783c3c68e8309a0f18a212f1af0fadd # v4
        with:
          category: "/language:${{matrix.language}}"
